#!/bin/bash

#PING=$(which ping)
#VBH=$(which VBoxHeadless)

#function waitForHost
# {
#    if [ -n "$1" ]; 
#    then
#        waitForHost1 $1;
#    else
#        echo "waitForHost: Hostname argument expected"
#    fi
#}

#function waitForHost1
# {
#    reachable=0;
#    while [ $reachable -eq 0 ];
#    do
#    $PING -q -c 1 $1 &
#    if [ "$?" -eq 0 ];
#    then
#        reachable=1
#    fi
#    done
#}

#$PING -q -c 1 "dev.loc"
#[[ $? != "0" ]] && $VBH --startvm debian-squeeze-new &
#
#waitForHost "dev.loc" #$1

CHROMIUM="/Applications/Chromium.app/Contents/MacOS/Chromium"
PS=$(which ps)

$PS -wxa | grep Chromium | grep -v grep

[[ $? == 1 ]] && $CHROMIUM --disable-web-security &